# Required
github_username: "tillson"
github_password: "a8ueifjq4jkasdfoiulk"
# Optional (comment out if not using)
# github_totp_seed: "ABCDEF1234567890" # Obtained via https://github.com/settings/two_factor_authentication/verify
